# Not working because test VMs had problems with network connectivity and I saw many i/o timeouts, DNS resolution errors, etc...
image: ubuntu1604

stack: node 8, docker

install:
  # - export APPVEYOR_SSH_BLOCK=true
  - curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  - ./tests/ci_test.sh
